version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/bbbeasy-backend"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/bbbeasy-docs"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/bbbeasy-frontend"
    schedule:
      interval: "daily"
