# Guest OS timezone
timezone: Africa/Tunis

# Are we need check box updates for every 'vagrant up'?
box_check_update: true

# Virtual machine name
machine_name: hivelvet

# Virtual machine IP
ip: 192.168.55.55

# Virtual machine CPU cores number
cpus: 2

# Virtual machine RAM
memory: 2048
