version: "3.8"

networks:
  hivelvet-network:
    ipam:
      config:
        - subnet: 172.55.0.0/24

services:
  webserver:
    restart: always
    image: nginx:1.23.3-alpine
    container_name: hv_nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      hivelvet-network:
        ipv4_address: 172.55.0.10
    volumes:
      - hivelvet-repo:/var/www/html
      - ./docker/hivelvet.conf:/etc/nginx/conf.d/default.conf:r
      - ./docker/default.ini:/var/www/hivelvet-backend/app/config/default.ini:r
      - ./docker/config-production.ini:/var/www/hivelvet/app/config/config-production.ini:r
      - ./docker/logs/backend:/var/www/hivelvet/logs/:rw
      - ./docker/logs/nginx:/var/log/nginx/:rw
  hivelvet:
    restart: always
    image: riadvice/hivelvet
    container_name: hv_app
    ports:
      - "9000:9000"
    networks:
      hivelvet-network:
        ipv4_address: 172.55.0.20
    volumes:
      - hivelvet-repo:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/conf.d/custom.ini:rw
      - ./docker/www-hivelvet.conf:/usr/local/etc/php-fpm.d/www-hivelvet.conf:rw
      - ./docker/config-production.ini:/var/www/hivelvet-backend/app/config/config-production.ini:r
      - ./docker/hvlogs/:/var/www/hivelvet-backend/logs/
      - ./docker/hvcache/:/var/www/hivelvet-backend/tmp/
  db:
    restart: always
    image: postgres:15.2-alpine3.17
    container_name: hv_db
    environment:
      POSTGRES_PASSWORD: hv
    networks:
      hivelvet-network:
        ipv4_address: 172.55.0.50
    volumes:
      - hivelvet-db-repo:/data/postgres
  cache:
    restart: always
    image: redis:7.0.9-alpine3.17
    container_name: hv_cache
    networks:
      hivelvet-network:
        ipv4_address: 172.55.0.60

volumes:
  hivelvet-repo:
  hivelvet-db-repo:
