version: "3.8"

networks:
  hivelvet-network:
    ipam:
      config:
        - subnet: 172.55.0.0/24

services:
  webserver:
    restart: always
    image: nginx:1.23.2-alpine
    container_name: hv_nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      hivelvet-network:
        ipv4_address: 172.55.0.10
    volumes:
      - hivelvet-backend-repo:/var/www/hivelvet-backend
      - hivelvet-frontend-repo:/var/www/hivelvet-installer
      - hivelvet-backend-repo:/var/www/hivelvet-docs
      - ./docker/hivelvet.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/default.ini:/var/www/hivelvet/app/config/default.ini:ro
      - ./docker/config-production.ini:/var/www/hivelvet/app/config/config-production.ini:ro
      - ./docker/backend-logs:/var/www/hivelvet/logs:rw
  hivelvet:
    restart: always
    image: riadvice/hivelvet
    container_name: hv_app
    ports:
      - "9000:9000"
    networks:
      hivelvet-network:
        ipv4_address: 172.55.0.20
    volumes:
      - hivelvet-backend-repo:/var/www/hivelvet-backend
      - hivelvet-frontend-repo:/var/www/hivelvet-installer
      - hivelvet-backend-repo:/var/www/hivelvet-docs
      - ./docker/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      - ./docker/www-hivelvet.conf:/usr/local/etc/php-fpm.d/www-hivelvet.conf:ro
  db:
    restart: always
    image: postgres
    container_name: hv_db
    environment:
      POSTGRES_PASSWORD: hv
    networks:
      hivelvet-network:
        ipv4_address: 172.55.0.50
    volumes:
      - hivelvet-db-repo:/data/postgres
  cache:
    restart: always
    image: redis:7.0.8-alpine
    container_name: hv_cache
    networks:
      hivelvet-network:
        ipv4_address: 172.55.0.60

volumes:
  hivelvet-backend-repo:
  hivelvet-frontend-repo:
  hivelvet-docs-repo:
  hivelvet-db-repo:
